### ISSUE TITLE
convert to python 3

### ISSUE THREAD

**Issue by Zamiell** [Rchardon/RebirthItemTracker#1]
Python 2 is end of life, so the codebase must eventually move to Python 3, the sooner the better.

This is actually a pretty easy conversion, all you have to do is convert some print statements and a few other misc. things.

However, it does break the auto updater, so some research has to be done to find a new solution.

its a good idea to do it now before you release tracker imo

**Comment by Rchardon** [comment]
Good suggestion, done !
