### ISSUE TITLE
"Removing collectible" text removes all items instead of just 1

### ISSUE THREAD

**Issue by Zamiell** [Rchardon/RebirthItemTracker#10]
For example, if I currently have 2 Death Touch collectibles, and I put the text "Removing collectible 237" in the log for the item tracker, then it should only remove 1 Death Touch collectible. Instead, it currently removes both Death Touches, which is a bug.

Because of this bug, the Racing+ Seeded 3 Dollar Bill collectible does not work properly.

**Comment by Rchardon** [comment]
I tested in vanilla and it doesn't. Verify that you're not putting the text twice in r+ code

**Comment by Zamiell** [comment]
you're right
