### ISSUE TITLE
Feature to have log messages write to a local file

### ISSUE THREAD

**Issue by Zamiell** [Rchardon/RebirthItemTracker#13]
## Feature Request

The item tracker should support reading a string of something like

```
[INFO] - Lua Debug: REBIRTH_ITEM_TRACKER_WRITE_TO_FILE This is an arbitrary message.
```

Upon reading this line, the item tracker will parse the text "This is an arbitrary message.".

Then, it will write the text to a file next to the item_tracker.exe called "mod_text.txt".

## Motivation

For the Babies Mod, I want people streaming the mod to be able to put a text capture in OBS of what the current baby description is.
In order to do this, you need to point OBS at a text file.

So, I would do the following inside of the mod:

```ts
function onNewBaby(babyDescription: BabyDescription) {
  Isaac.DebugString(`REBIRTH_ITEM_TRACKER_WRITE_TO_FILE ${baby.description}`);
}
```

And then end-users would point their OBS at "mod_text.txt".

**Comment by Rchardon** [comment]
Feature added in 3.2.6 version
