### ISSUE TITLE
Feature to show what player picked a certain item.

### ISSUE THREAD

**Issue by la-pandev** [Rchardon/RebirthItemTracker#16]
I'd be nice if there was an option to show what player picked a certain item. I see that the program already shows all picked items regardless of player, so maybe we can add a little indicator next to each item that displays a texts that says "P1", "P2", etc.. Or maybe each item can have a colored outline or glowing effect, and player 1 would have all items colored in red, player 2 in blue, etc.

**Comment by Rchardon** [comment]
The log doesn't provide enough informations for that, everything would broke when Strawman or Soul of Forgotten/J&E is used because it spawns new players
