### ISSUE TITLE
cx_Freeze

### ISSUE THREAD

**Issue by ghost** [Rchardon/RebirthItemTracker#17]
Hello,
I keep getting this error
![Screenshot 2024-11-11 175244](https://github.com/user-attachments/assets/0d57f2c6-f9e4-4d46-829e-198c6e0e3fde)
The tracker is in this directory : "C:\Tracker\Rebirth.Item.Tracker-3.3.6\Rebirth Item Tracker\Rebirth Item Tracker.exe"
Thanks

**Comment by ghost** [comment]
What happens is that I can open it only once right after extracting the zip file. After that, I encounter an error whenever I try to open it again. The only solution I've found so far is to delete the folder and extract everything again. Thanks in advance for your help

**Comment by aymericingargiola** [comment]
The last version seems to be 3.3.8 not 3.3.6, maybe you should try again with the last version : https://github.com/Rchardon/RebirthItemTracker/releases/latest

If you still get the error, you can try to run the app as administrator

**Comment by ghost** [comment]
So I tried with the latest version and I still get the same error, then I tried to run it as administrator and same error too 🫤
![Screenshot 2024-11-12 152956](https://github.com/user-attachments/assets/f091671d-2e97-4275-92a9-5e15eed8a3fd)

**Comment by Rchardon** [comment]
Hello, réessaye voir sur la dernière version ? J'ai tenté un fix mais c'est ultra galère à débugger vu que j'ai pas le problème (Deja j'arrive pas à fixer le problème de mon chemin perso qui apparait dans l'erreur c'est relou)

**Comment by ghost** [comment]
> Hello, réessaye voir sur la dernière version ? J'ai tenté un fix mais c'est ultra galère à débugger vu que j'ai pas le problème (Deja j'arrive pas à fixer le problème de mon chemin perso qui apparait dans l'erreur c'est relou)

Merci pour ta réponse, alors j'ai toujours le problème malheureusement, tu veux call discord rapidement que je puisse te partager l'écran?

**Comment by Rchardon** [comment]
On peut, mon pseudo discord c'est gamonymous
