### ISSUE TITLE
Win7 compatibility 

### ISSUE THREAD

**Issue by Stally18** [Rchardon/RebirthItemTracker#2]
Is it possible to use new tracker on windows7?
api-ms-win-core-path.dll error on launch

or maybe you have that previous version before you converted everything to Py 3.9, bc thats probably the case, Py 3.9 unsopported on win7

**Comment by Hyphen-ated** [comment]
The 3.8 series still works on windows 7, you could try installing python 3.8.9 and running the tracker yourself from source if rchardon decides not to support windows 7

**Comment by Stally18** [comment]
Yeah, its just what i did, a bit complicated, but at least working solution

**Comment by Rchardon** [comment]
Yeah I approve what hyphen said. Win7 is like 11ish years old and long-time support is gone, Win7 is bound to die anyway unlike Win10 which is and will stay the last Windows OS.
