### ISSUE TITLE
More URL placeholders?

### ISSUE THREAD

**Issue by TheChilliPL** [Rchardon/RebirthItemTracker#3]
Right now, as in view.py, the only placeholder possible for the URL option is $ID:

https://github.com/Rchardon/RebirthItemTracker/blob/aff4a10e6c3ff4666ec6d6421c8ae3cf0e979451/src/view_controls/view.py#L778-L783

I'd suggest adding more so the user can replace this with any website, even Google.
The most obvious example would be the item name (but that shouldn't insert spaces itself, rather %20 or + (for query strings)

**Comment by TheChilliPL** [comment]
Uh, actually even this doesn't work. For some reason, the `load_detail_page` function is never used in code.
Tried to implement some simple placeholders for name:
```py
    def load_detail_page(self):
        url = Options().item_details_link
        if not url:
            return
        url = url.replace("$ID", self.item.item_id)
        name = self.item.name
        name_uri = url_parse.quote(name)
        name_query = url_parse.quote_plus(name)
        name_undersc = name_uri.replace("%20", "_")
        url = url.replace("$NAME_Q", name_query)
        url = url.replace("$NAME_U", name_undersc)
        url = url.replace("$NAME", name_uri)
        webbrowser.open(url, autoraise=True)
```

**Comment by TheChilliPL** [comment]
And there's actually a 5-and-a-half-year-old typo at line 45 of `view.py`
https://github.com/Rchardon/RebirthItemTracker/blob/34906d91cf3b20ac8f6bcd5a5934bbd112b2b4f3/src/view_controls/view.py#L45
PyCharm can't even find any usage of this class

**Comment by Rchardon** [comment]
Hello, i will check that later since most of the wiki pages aren't updated yet. My priority now is to update everything for Repentance + fix some rare crashes/bug. If you wanna do a pull request now, go ahead. I fixed the typo tho, thank you !

**Comment by TheChilliPL** [comment]
I'd gladly do a pull request, but the clicking doesn't seem to work either and I'm not actually sure how to fix that (I barely used Python, and never tried PyGame)

**Comment by Rchardon** [comment]
I removed this part. It's not like people were asking this and left click on the items is common and can lead to accidental pages opened. Setting this on a key from keyboard is also tedious
