### ISSUE TITLE
The tracker should remember items after closing the game

### ISSUE THREAD

**Issue by Zamiell** [Rchardon/RebirthItemTracker#4]
As a run progresses, the tracker should back up the current items to a file "current_run_items.json".

Subsequently, when a run is started, the tracker uses logic to determine whether it is:
1) a new run
2) a continued run

If it is a continued run, and this is the first run loaded for the respective log.txt file, then the tracker should load the items from the ""current_run_items.json"" file and assume that they have been gotten on this run.

Unfortunately, this will cause bugs in the case where:
1) the player is playing a run on the 1st save slot
2) they saves & quit
3) they exit the game
4) they open the game
5) they continue a run on the 2nd save slot
6) they will "get" the items from the first run

However, this seems unlikely to happen.

**Comment by Rchardon** [comment]
Added in 3.1.0

**Comment by Zamiell** [comment]
Horray, thanks Gamon.
